### ISSUE TITLE
健康检查结果不对

### ISSUE THREAD

**Issue by idmaoning** [zhouchangxun/ngx_healthcheck_module#25]
监控了两个udp服务，然后把两个服务都停掉，状态还是up

**Comment by Veduco** [comment]
UDP health check always returns true.
Any upstreams monitored with UDP don't accurately reflect the endpoints status.

**Comment by ice2lin** [comment]
udp 的健康检查还是有问题，随便填一个 udp 结果都是 true

**Comment by zhouchangxun** [comment]
@idmaoning @Veduco @ice2lin ：
The root cause is that I hadn't set default check data which cause the checker didn't send check packet. 
I fixed it in this commit: https://github.com/zhouchangxun/ngx_healthcheck_module/commit/6188804cca51d149f773dbab3659e534de799ed8

Anyway, thank you for you guys' feedback :D

**Comment by zhouchangxun** [comment]
Please write here if the patch works and I will close this issue after that.

**Comment by zhouchangxun** [comment]
UDP check depends on icmp reply(port/host unreachable).
So please make sure icmp can work between nginx and backend server otherwise it will assume backend is alive if no any icmp reply.

**Comment by sola97** [comment]
那个nginx_healthcheck_for_nginx_1.16+.patch是不是没有更新过，我不知道该怎么更新。。

**Comment by sola97** [comment]
那个nginx_healthcheck_for_nginx_1.16+.patch是不是好久没更新了，怎么更新？
